return {
  -- Nightfox colorscheme
  {
    "EdenEast/nightfox.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      palettes = {
        carbonfox = {
          bg0 = "#000000",
          bg1 = "#050505",
          bg2 = "#0c0c0c",
          bg3 = "#151515",
          fg1 = "#f2f2f2",
          fg2 = "#d0d0d0",
          fg3 = "#a6a6a6",
          blue = "#6cb6ff",
          cyan = "#4adfff",
          green = "#7dff9a",
          orange = "#ff9a5c",
          pink = "#ff6bd5",
          purple = "#b07aff",
          red = "#ff5c57",
          yellow = "#ffd966",
        },
      },
      options = {
        -- Compiled file's destination location
        compile_path = vim.fn.stdpath("cache") .. "/nightfox",
        compile_file_suffix = "_compiled", -- Compiled file suffix
        transparent = false, -- Disable setting background
        terminal_colors = true, -- Set terminal colors (msys2 and guifont and win32 excluded)
        dim_inactive = false, -- Non-focused windows shadowed
        module_default = true, -- Default enable value for modules
        styles = { -- Style to be applied to different syntax groups
          comments = "NONE", -- Value is any valid attr-list value `:help attr-list`
          conditionals = "NONE",
          constants = "NONE",
          functions = "NONE",
          keywords = "NONE",
          numbers = "NONE",
          operators = "NONE",
          strings = "NONE",
          types = "NONE",
          variables = "NONE",
        },
        inverse = { -- Inverse highlight for different types
          match_paren = false,
          visual = false,
          search = false,
        },
      },
      groups = {
        all = {
          Normal = { fg = "palette.fg1", bg = "palette.bg0" },
          NormalNC = { fg = "palette.fg2", bg = "palette.bg0" },
          NormalFloat = { bg = "palette.bg0" },
          FloatBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          CursorLine = { bg = "palette.bg1" },
          CursorLineNr = { fg = "palette.yellow", bg = "palette.bg1", style = "bold" },
          Cursor = { fg = "palette.bg0", bg = "palette.cyan" },
          CursorInsert = { fg = "palette.bg0", bg = "palette.orange" },
          LineNr = { fg = "palette.fg3" },
          Visual = { fg = "palette.bg0", bg = "#ffdba3" },
          Search = { fg = "palette.bg0", bg = "palette.yellow", style = "bold" },
          IncSearch = { fg = "palette.bg0", bg = "palette.orange", style = "bold" },
          MatchParen = { fg = "palette.bg0", bg = "palette.cyan", style = "bold" },
          WinSeparator = { fg = "palette.cyan" },
          Comment = { fg = "palette.fg3", style = "italic" },
          String = { fg = "palette.green" },
          Function = { fg = "palette.blue", style = "bold" },
          Keyword = { fg = "palette.pink", style = "bold" },
          Type = { fg = "palette.cyan" },
          Constant = { fg = "palette.orange" },
          Number = { fg = "palette.orange" },
          Boolean = { fg = "palette.orange" },
          Identifier = { fg = "palette.fg1" },
          Statement = { fg = "palette.pink", style = "bold" },
          PreProc = { fg = "palette.purple" },
          Operator = { fg = "palette.cyan" },
          Special = { fg = "palette.blue" },
          Delimiter = { fg = "palette.fg2" },
          Title = { fg = "palette.blue", style = "bold" },
          Todo = { fg = "palette.bg0", bg = "palette.yellow", style = "bold" },
          DiagnosticError = { fg = "palette.red" },
          DiagnosticWarn = { fg = "palette.yellow" },
          DiagnosticInfo = { fg = "palette.cyan" },
          DiagnosticHint = { fg = "palette.green" },
          Folded = { fg = "palette.fg3", bg = "palette.bg1" }, -- UFO folded lines
          UfoFoldedFg = { fg = "palette.fg1" },
          UfoFoldedBg = { bg = "palette.bg1" },
          AerialNormal = { bg = "palette.bg0" },
          AerialLine = { bg = "palette.bg1", fg = "palette.blue" },
          TabLine = { fg = "palette.fg3", bg = "palette.bg1" },
          TabLineSel = { fg = "palette.fg1", bg = "palette.bg0", style = "bold" },
          TabLineFill = { bg = "palette.bg1" },
          BufferLineFill = { bg = "palette.bg1" },
          BufferLineBackground = { fg = "palette.fg3", bg = "palette.bg1" },
          BufferLineBuffer = { fg = "palette.fg3", bg = "palette.bg1" },
          BufferLineBufferVisible = { fg = "palette.fg2", bg = "palette.bg1" },
          BufferLineBufferSelected = { fg = "palette.fg1", bg = "palette.bg0", style = "bold" },
          BufferLineTab = { fg = "palette.fg3", bg = "palette.bg1" },
          BufferLineTabSelected = { fg = "palette.fg1", bg = "palette.bg0", style = "bold" },
          BufferLineTabClose = { fg = "palette.fg2", bg = "palette.bg1" },
          BufferLineIndicatorSelected = { fg = "palette.cyan", bg = "palette.bg0" },
          BufferLineModified = { fg = "palette.yellow", bg = "palette.bg1" },
          BufferLineModifiedVisible = { fg = "palette.yellow", bg = "palette.bg1" },
          BufferLineModifiedSelected = { fg = "palette.yellow", bg = "palette.bg0", style = "bold" },
          BufferLineSeparator = { fg = "palette.bg1", bg = "palette.bg1" },
          BufferLineSeparatorVisible = { fg = "palette.bg1", bg = "palette.bg1" },
          BufferLineSeparatorSelected = { fg = "palette.bg1", bg = "palette.bg0" },
          BlinkCmpMenu = { bg = "palette.bg0" },
          BlinkCmpMenuBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          BlinkCmpDoc = { bg = "palette.bg0" },
          BlinkCmpDocBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          BlinkCmpLabelMatch = { fg = "palette.blue", style = "bold" },
          BlinkCmpLabel = { fg = "palette.fg1" },
          BlinkCmpLabelDeprecated = { fg = "palette.fg3", style = "strikethrough" },
          BlinkCmpKind = { fg = "palette.pink" },
          BlinkCmpMenuSelection = { fg = "palette.fg1", bg = "palette.bg2", style = "bold" },
          Pmenu = { bg = "palette.bg0" },
          PmenuSel = { fg = "palette.fg1", bg = "palette.bg2", style = "bold" },
          PmenuSbar = { bg = "palette.bg1" },
          PmenuThumb = { bg = "palette.cyan" },
          SnacksPickerBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          SnacksPickerTitle = { fg = "palette.cyan", bg = "palette.bg0" },
          SnacksPickerInputBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          SnacksPickerPreviewBorder = { fg = "palette.cyan", bg = "palette.bg0" },
          SnacksPickerListBorder = { fg = "palette.cyan", bg = "palette.bg0" },
        },
      },
    },
  },

  -- Configure LazyVim to load carbonfox
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "carbonfox",
    },
  },
}
